from .article_sap import ArticleSap
from .categorie import Categorie
from .categprix import CategPrix
from .classe_client import ClasseClient
from .coefprest import CoefPrest
from .generaux import Generaux
from .granted import Granted
from .groupe import Groupe
from .machine import Machine
from .paramtexte import Paramtexte
from .plateforme import Plateforme
from .prestation import Prestation
from .user_labo import UserLabo